API to import/export menu
Bitergia/bitergia-analytics-plugin pull request #19
Opened 2022-08-08 15:37 UTC by evamillan

- Unifies the routes to import and export the menu data into a single one with a GET and a PUT method:  `/_plugins/_bap/metadashboard`.
- Updates the README.
- Adds tests for the API. The tests can be run with `yarn test:api`.
- Adds a GitHub action that runs the tests.

2022-09-09 15:02 UTC, sduenas requested changes
LGTM. It works as expected but I added some minor comments.

2022-09-09 15:02 UTC, sduenas commented on README.md
> + GET /_plugins/_bap/metadashboard
You can add an example with `curl` to run the command.

2022-09-09 15:02 UTC, sduenas commented on babel.config.js
> + };
Initial white spaces should be removed.

2022-09-09 15:02 UTC, sduenas commented on public/components/dragDropEditor.tsx
> +      const response = await http.put(`${API_PREFIX}/metadashboard`, {
A better name would be `menu` because we only add data for the bap menu and not something else.

2022-09-09 16:05 UTC, evamillan commented
@sduenas I've added the example, removed the white spaces and renamed all references from "metadashboard" to "menu". This means that all menus will need to be updated once this is in production.

2022-09-20 22:25 UTC, sduenas approved these changes
LGTM

2022-09-20 22:41 UTC, merged